---
title: "R Notebook"
output: html_notebook
---
```{r}
library(ggplot2)
datos <- read.csv("Precios.csv")
datos
```
```{r}
getwd()
```
```{r}
archivo <- file.path("Escritorio", "R", "Precios.csv")
datos <- read.csv(archivo)
datos
```
```{r}
# Obtiene la ruta del escritorio
ruta_escritorio <- file.path(Sys.getenv("USERPROFILE"), "Escritorio")

# Construye la ruta completa al archivo
archivo <- file.path(ruta_escritorio, "R", "Precios.csv")

# Verifica la ruta del archivo
print(archivo)

# Intenta leer el archivo
datos <- read.csv(archivo)

```
```{r}
archivo <- file.path("C:/Users/pablo/OneDrive/Escritorio/R", "Precios.csv")
datos <- read.csv(archivo)
datos
```
```{r}
library(ggplot2)
archivo <- file.path("C:/Users/pablo/OneDrive/Escritorio/R", "Precios.csv")
datos <- read.csv(archivo)
p <- ggplot(datos)
p <- p + aes(x = Indice, y = Dolar)
p <- p + geom_line(linetype = 6, size = 1, colour = "#FA8072", alpha = 0.8)
p <- p + geom_point(shape = 16, size = 1.8, colour = "#CD5C5C", ALPHA = 0.9)
p <- p + xlab("Días Transcurridos")
p <- p + ylab("Tasa de cambio /n del dólar")
p <- p + ggtitle("Fluctuacion del dolar", subtitle = "18/feb - 31/may")
p

```

```{r}
library(ggplot2)
archivo <- file.path("C:/Users/pablo/OneDrive/Escritorio/R", "Precios.csv")
datos <- read.csv(archivo)
p <- ggplot(datos)
p <- p + aes(x = Petroleo, y = Dolar, colour = Mes, shape = Mes, size = Mes)
p <- p + scale_shape_manual(values = c(16, 17, 15, 18))
p <- p + scale_color_manual(values = c("purple", "brown","orange", "darkred" ))
p <- p + scale_size_manual(values = c(2, 2, 1.8, 2.5))
p <- p + geom_point()
p <- p + xlab("Precio del petroleo")
p <- p + ylab("Tasa de cambio /n del dolar")
p <- p + ggtitle("Petroleo vs Dolar", subtitle = "18/feb - 31/may")
p
```

